# Site
name: 'Quicklook'
description: 'Quicklook’s corporate mission is “to organize the world’s product information and make it symmetric and useful.” Our business philosophy is “continuous improvement to survive and develop”. Our goal is “to global brand”'
logo: ''
favicon: '/assets/images/fit/32/1_m-R_BkNf1Qjr1YbyOIJY2w.png'
baseurl: '/'
url: "https://quicklooked.github.io/"
disqus: ''
email: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    quicklooked:
      name:           Quicklook
      site:           https://quicklooked.github.io/@quicklook
      avatar:         ''
      bio:            ""
      email:          
      twitter:        

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: 
      author: 
      avatar: ''
      
  # all pages 
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# _headers
/*
  Permissions-Policy: interest-cohort=()

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Gitalk
gitalk:
  enable: true
  clientID: 7d1d6e81e49f1c4dbfaf
  clientSecret: 1894a92f91de7a8ce4d2cba4ae27ac2b1f1dad00
  repo: Gitalk
  owner: quicklooked
  admin: quicklooked
  distractionFreeMode: false
